config/routes.rb
# config/routes.rb
Rails.application.routes.draw do
  root to: 'weather#index'
  get 'weather/forecast'
  post 'weather/forecast', to: 'weather#forecast'
  get 'weather/current_weather_conditions'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :danger, :error
end

app/controllers/weather_controller.rb
# app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  TO_CELC = 273.15

  def index
  end

  def forecast
    api_key = Rails.application.credentials[:development][:open_weather_map][:api_key]
    service = OpenWeatherMap::Forecast.new(api_key)

    flash[:danger] = 'City or Country not available.' and redirect_to request.referer || root_path and return if !(Geocoder.search(params[:city]).present?)

    response = service.forecast(params[:city])

    flash[:danger] = "#{response["message"]}" and redirect_to request.referer || root_path and return if response["cod"] == "400"

    grouped_data = response['list'].group_by { |item| Date.parse(item['dt_txt']).strftime('%Y-%m-%d') }

    # Find the highest and lowest values for each group
    @daily_data = {}
    grouped_data.each do |date, items|
      temps = items.map { |item| item['main']['temp'] }
      @daily_data[date] = {
        'max_temp' => (temps.max - TO_CELC).round(2),
        'min_temp' => (temps.min - TO_CELC).round(2) ,
        'weather' => items.first['weather'][0]['description']
      }
    end

    @respons ||= current_weather_conditions(params[:city]) 

    flash[:danger] = "#{@respons["message"]}" and redirect_to request.referer || root_path and return if @respons["cod"] == "404"    

    if @daily_data.present?
      render :forecast
    else
      render :index
    end
  end

  def current_weather_conditions(city)
    api_key = Rails.application.credentials[:development][:open_weather_map][:api_key]
    service = OpenWeatherMap::Forecast.new(api_key)
    service.retrieve_current_weather_conditions(city)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def get_image_by_weather(value)
    case value

    when "clear sky"
      "https://kamleshyadav.com/templatemonster-html/weather/assets/images/wea-icons/icon-06.png"
    when "rain", "shower rain"
      "https://kamleshyadav.com/templatemonster-html/weather/assets/images/wea-icons/icon-03.png"
    when "light rain"
      "https://kamleshyadav.com/templatemonster-html/weather/assets/images/wea-icons/icon-04.png"
    when "few clouds"
      "https://kamleshyadav.com/templatemonster-html/weather/assets/images/wea-icons/icon-07.png"
    when "thunderstorm"
      "https://kamleshyadav.com/templatemonster-html/weather/assets/images/wea-icons/icon-02.png"
    when "overcast clouds", "scattered clouds"
      "https://kamleshyadav.com/templatemonster-html/weather/assets/images/wea-icons/icon-01.png"
    when "broken clouds"
      "https://kamleshyadav.com/templatemonster-html/weather/assets/images/wea-icons/icon-08.png"
    else
    end
  end
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewWeather</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>
    <% flash.each do |type, msg| %>
      <div class="alert alert-danger"  id="flash_id" role="alert">
        <%= msg %>
      </div>
    <% end %>
    <%# flash.clear %>
    <%= yield %>
  </body>
</html>

app/views/weather/_header_search.html.erb
<div class="wea_header_main_menus snipcss-2M5Zy">
  <div class="wea_logo">
    <a href="index.html">
      <img src="https://kamleshyadav.com/templatemonster-html/weather/assets/images/logo.png" alt="logo">
    </a>
  </div>
  
  <div class="wea_main_menu main_menu_parent" style="margin-right: 40%;">
    <div class="wed_nav_items main_menu_wrapper text-right wed_single_index_menu">
      <ul>
        <form class="form-inline my-2 my-lg-0" id="search-form" action="<%= weather_forecast_path %>" method="get">
          <input class="form-control mr-sm-2" pattern="^[A-Za-z]+" title="Please enter alphabets only" id="search-input" name="city" value="" type="search" placeholder="Weather in your city" aria-label="Search" >

          <button class="btn btn-outline-success my-2 my-sm-0" pattern="^[A-Za-z]+" title="Please enter alphabets only" id="example-button" type="submit">Search</button>
        </form>
      </ul>
    </div>
  </div>
</div>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'style' %>
<% end %>  

app/views/weather/_weather_card_data.html.erb
<% daily_data.map {|date, value| [date, value]}.each do |date, value| %>
  <div class="wea_commonday">
    <h4>
      <%=  date.to_date %><br>
    </h4>
    <img src= <%= get_image_by_weather(value["weather"])%> alt="icon7">
    <h6>
      <%= "#{value["max_temp"]} &#8451; (Max)".html_safe %><br>
      <%= "#{value["min_temp"]} &#8451; (Min)".html_safe %><br>
      <%= "#{value["weather"]}" %>
    </h6>
  </div>
<% end %>

app/views/weather/_weather_description.html.erb
<div class="row">
  <div class="col-lg-4 col-md-6">
    <div class="wea_weather_sun_wrapper">
      <div class="wea_weather_sunrise">
        <h5>
          sunrise
        </h5>  
        <p>
          <%= "#{Time.at(response["sys"]["sunrise"]).strftime("%H:%M %p")}" %>
        </p>
      </div>
      
      <div class="wea_weather_sunset">
        <h5>
          sunset
        </h5>
        <p>
          <%= "#{Time.at(response["sys"]["sunset"]).strftime("%H:%M %p")}" %>
        </p>
      </div>
    </div>
    
    <div class="wea_weather_dir">
      <div class="wea_wind">
        <h4>
          wind status
        </h4>
        <p>
          <%= "#{response["wind"]["speed"]}" %>
          <span>
            Km/h
          </span>
        </p>
      </div>
      
      <div class="wea_wind">
        <h4>
          rain status
        </h4>
        <p>
          <%= "#{@respons["clouds"]["all"]}%" %>
        </p>
      </div>
      
      <div class="wea_wind">
        <h4>
          visibility
        </h4>
        <p>
          <%= "#{response["visibility"]}" %>
          <span>
            m
          </span>
        </p>
    </div>
  </div>
</div>

app/views/weather/_weather_list_description.html.erb
<div class="wea_list_heading">
  <h4>
    today
  </h4>
  <h5>
    <%= Date.today.strftime('%d/%m/%Y %A') %>
  </h5>
</div>

<div class="wea_list_rain">
  <ul>
    <li>
      <p>Humidity</p>
      <h3>
        <%= "#{@respons["main"]["humidity"]}%" %>
      </h3>
    </li>
    <li>
      Weather
      <h3>
        <%= @respons["weather"][0]["description"] %>
      </h3>
    </li>
    <li>
      Cordinates
      <h3>
        <td><%= "Long: #{@respons["coord"]["lon"]} <br>  Lat: #{@respons["coord"]["lat"]}".html_safe %>
      </h3>
    </li>
    <li>
      City
      <h3>
        <td><%= "#{@respons["name"]}, (#{@respons["sys"]["country"]})" %>
    </li>
    <li>
      Pressure
      <h3>
        <%= "#{@respons["main"]["pressure"]} hPa" %>
      </h3>
    </li>
    <li>
      Clouds
      <h3>
        <%= "#{@respons["clouds"]["all"]}%" %>
      </h3>
    </li>
  </ul>
</div>

app/views/weather/_weekly_forecast.html.erb
<h4>
  <%= "Feels Like #{(response["main"]["feels_like"] - 273.15).round(2)} &#8451;<br>".html_safe %>
</h4>

<p>
  (Min)
  <%= daily_data.map {|date, value| [date, value]}.first[1]["min_temp"] %>
  <sup>
    &#8451;
  </sup>
  (Max)
  <%= daily_data.map {|date, value| [date, value]}.first[1]["max_temp"] %>
  <sup>
    &#8451;
  </sup>
</p>

app/views/weather/forecast.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Weather Forecast</title>
  </head>
  <body>
    <%= render partial: "header_search" %>

    <section class="wea_weather_detail snipcss-BHQRh">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="wea_heading_wrapper">
              <h3>
                Weather Forecast
              </h3>
            </div>
          </div>
        </div>
        <%= render partial: "weather_description", locals: { response: @respons } %>

        <div class="col-lg-3 col-md-6">
          <div class="wea_weather_today">
            <%= render partial: "weekly_forecast", locals: { response: @respons, daily_data: @daily_data } %>
          </div>
        </div>
        
        <div class="col-lg-5 col-md-12">
          <div class="wea_weather_list">
            <%= render partial: "weather_list_description", locals: { response: @respons, daily_data: @daily_data } %>
          </div>
        </div>
      </div>
      
      <div class=" wea_weekly_wrapper wea_heading_wrapper wea_weekly_head"  >
        <h3>weekly Weather Forecast</h3>
      </div>
      
      <div class="wea_weekly_weather snipcss-oYHxx" style="background-color: #fff;">
        <%= render partial: "weather_card_data", locals: { daily_data: @daily_data } %>
      </div>
    </section>
  </body>
</html>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'style' %>
<% end %>

app/views/weather/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  
  <body class="index-class">
    <%= render partial: "header_search" %>
  </body>
</html>